version: '3.10'

services:
  boiler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/boiler
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    env_file:
      - .env
